// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SwitchOn_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
lv_obj_t * ui_screenMain;
lv_obj_t * ui_tabsMain;

lv_obj_t * ui_tabWidget;
lv_obj_t * ui_cntWidgets;

lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Chart1;

lv_obj_t * ui_tabMacros;
lv_obj_t * ui_cntMacros;

lv_obj_t * ui_pnlStatus;
lv_obj_t * ui_pnlStatusLeft;
lv_obj_t * ui_pnlStatusRight;
lv_obj_t * ui_cntProfile;
lv_obj_t * ui_lblProfile;
lv_obj_t * ui_ddProfile;

void ui_event_btnWifi(lv_event_t * e);
lv_obj_t * ui_btnWifi;
lv_obj_t * ui_lblWifi;

void ui_event_btnSetting(lv_event_t * e);
lv_obj_t * ui_btnSetting;
lv_obj_t * ui_lblSetting;

lv_obj_t * ui_lblBluetooth;
lv_obj_t * ui_lblCompanion;
lv_obj_t * ui_lblSD;

// SCREEN: ui_screenWifi
void ui_screenWifi_screen_init(void);
lv_obj_t * ui_screenWifi;
lv_obj_t * ui_cntWifi;
lv_obj_t * ui_cntWifiSettings;
lv_obj_t * ui_cnt1;
lv_obj_t * ui_lblWifiSSID;
lv_obj_t * ui_ddWifiSSID;
lv_obj_t * ui_cnt2;
lv_obj_t * ui_lblWifiPass;
void ui_event_txtWifiPass(lv_event_t * e);
lv_obj_t * ui_txtWifiPass;
lv_obj_t * ui_cntWifiHostname;
lv_obj_t * ui_lblWifiHostname;
void ui_event_txtWifiHostname(lv_event_t * e);
lv_obj_t * ui_txtWifiHostname;
lv_obj_t * ui_cnt3;
void ui_event_btnWifiAction(lv_event_t * e);
lv_obj_t * ui_btnWifiAction;
lv_obj_t * ui_lblWifiAction;
void ui_event_btnWifiScan(lv_event_t * e);
lv_obj_t * ui_btnWifiScan;
lv_obj_t * ui_lblWifiScan;
lv_obj_t * ui_cnt4;
lv_obj_t * ui_lblWifiIP;
lv_obj_t * ui_lblWifiRSSI;
lv_obj_t * ui_cntWifiBottom;
void ui_event_btnWifiManagerClose(lv_event_t * e);
lv_obj_t * ui_btnWifiManagerClose;
void ui_event_lblWifiManagerClose(lv_event_t * e);
lv_obj_t * ui_lblWifiManagerClose;
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_pnlWifiSpinner;
lv_obj_t * ui_wifiSpinner;


// SCREEN: ui_screenSettings
void ui_screenSettings_screen_init(void);
lv_obj_t * ui_screenSettings;
lv_obj_t * ui_cntSettings;
lv_obj_t * ui_cntSettings4;
lv_obj_t * ui_lblScreenRotate;
void ui_event_dropdownScreenRotate(lv_event_t * e);
lv_obj_t * ui_dropdownScreenRotate;
lv_obj_t * ui_cntSettings1;
lv_obj_t * ui_lblScreenRotate;
void ui_event_dropdownGridStyle(lv_event_t * e);
lv_obj_t * ui_dropdownGridStyle;
lv_obj_t * ui_cntSettings3;
lv_obj_t * ui_lblReverse;
void ui_event_swReverseColor(lv_event_t * e);
lv_obj_t * ui_swReverseColor;
lv_obj_t * ui_sliderBrightness;
lv_obj_t * ui_swBluetooth;
void ui_event_swBluetooth(lv_event_t * e);
lv_obj_t * ui_cntSettingsBottom;
void ui_event_btnSettingsClose(lv_event_t * e);
lv_obj_t * ui_btnSettingsClose;
void ui_event_lblSettingsClose(lv_event_t * e);
lv_obj_t * ui_lblSettingsClose;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
/* LV_COLOR_16_SWAP check removed - not applicable in LVGL v9 */

///////////////////// ANIMATIONS ////////////////////
void SwitchOn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 10);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

void ui_event_btnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenWifi, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenWifi_screen_init);
    }
}
void ui_event_btnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenSettings_screen_init);
    }
}

/**
 * Wifi Manager
*/

void ui_event_txtWifiPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_txtWifiPass);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_txtWifiHostname(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard, ui_txtWifiHostname);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_btnWifiAction(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnWifiChangeState(e);
    }
}
void ui_event_btnWifiScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnWifiScan(e);
    }
}
void ui_event_btnWifiManagerClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenMain, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenMain_screen_init);
    }
}

/**
 * Settings
*/

void ui_event_dropdownScreenRotate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnScreenRotateChange(e);
    }
}
void ui_event_dropdownGridStyle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnCardSizeChange(e);
    }
}
void ui_event_swReverseColor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnReverseColorSwitchChange(e);
    }
}
void ui_event_btnSettingsClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenMain, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenMain_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        OnSettingsClose(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_simple_init(dispp);
    lv_disp_set_theme(dispp, theme);

    ui_screenMain_screen_init();
    ui_screenWifi_screen_init();
    ui_screenSettings_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_screenMain);
}
