// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void SwitchOn_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
extern lv_obj_t * ui_screenMain;
extern lv_obj_t * ui_tabsMain;

extern lv_obj_t * ui_tabWidget;
extern lv_obj_t * ui_cntWidgets;

extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Chart1;

extern lv_obj_t * ui_tabMacros;
extern lv_obj_t * ui_cntMacros;
extern lv_obj_t * ui_tabKeyboard;

void ui_macrosTab_init(lv_obj_t * comp_parent);
void ui_widgetsTab_init(lv_obj_t * comp_parent);
void ui_keyboardTab_init(lv_obj_t * comp_parent);

extern lv_obj_t * ui_pnlStatus;
extern lv_obj_t * ui_pnlStatusLeft;
extern lv_obj_t * ui_pnlStatusRight;
extern lv_obj_t * ui_cntProfile;
extern lv_obj_t * ui_lblProfile;
extern lv_obj_t * ui_ddProfile;

void ui_event_btnWifi(lv_event_t * e);
extern lv_obj_t * ui_btnWifi;
extern lv_obj_t * ui_lblWifi;

void ui_event_btnSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSetting;
extern lv_obj_t * ui_lblSetting;

extern lv_obj_t * ui_lblBluetooth;
extern lv_obj_t * ui_lblCompanion;
extern lv_obj_t * ui_lblSD;

// SCREEN: ui_screenWifi
void ui_screenWifi_screen_init(void);
extern lv_obj_t * ui_screenWifi;
extern lv_obj_t * ui_cntWifi;
extern lv_obj_t * ui_cntWifiSettings;
extern lv_obj_t * ui_cnt1;
extern lv_obj_t * ui_lblWifiSSID;
extern lv_obj_t * ui_ddWifiSSID;
extern lv_obj_t * ui_cnt2;
extern lv_obj_t * ui_lblWifiPass;
void ui_event_txtWifiPass(lv_event_t * e);
extern lv_obj_t * ui_txtWifiPass;
extern lv_obj_t * ui_cntWifiHostname;
extern lv_obj_t * ui_lblWifiHostname;
void ui_event_txtWifiHostname(lv_event_t * e);
extern lv_obj_t * ui_txtWifiHostname;
extern lv_obj_t * ui_cnt3;
void ui_event_btnWifiAction(lv_event_t * e);
extern lv_obj_t * ui_btnWifiAction;
extern lv_obj_t * ui_lblWifiAction;
void ui_event_btnWifiScan(lv_event_t * e);
extern lv_obj_t * ui_btnWifiScan;
extern lv_obj_t * ui_lblWifiScan;
extern lv_obj_t * ui_cnt4;
extern lv_obj_t * ui_lblWifiIP;
extern lv_obj_t * ui_lblWifiRSSI;
extern lv_obj_t * ui_cntWifiBottom;
void ui_event_btnWifiManagerClose(lv_event_t * e);
extern lv_obj_t * ui_btnWifiManagerClose;
void ui_event_lblWifiManagerClose(lv_event_t * e);
extern lv_obj_t * ui_lblWifiManagerClose;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_pnlWifiSpinner;
extern lv_obj_t * ui_wifiSpinner;

// SCREEN: ui_screenSettings
void ui_screenSettings_screen_init(void);
extern lv_obj_t * ui_screenSettings;
extern lv_obj_t * ui_cntSettings;
extern lv_obj_t * ui_cntSettings4;
extern lv_obj_t * ui_lblScreenRotate;
void ui_event_dropdownScreenRotate(lv_event_t * e);
extern lv_obj_t * ui_dropdownScreenRotate;
extern lv_obj_t * ui_cntSettings1;
extern lv_obj_t * ui_lblScreenRotate;
void ui_event_dropdownGridStyle(lv_event_t * e);
extern lv_obj_t * ui_dropdownGridStyle;
extern lv_obj_t * ui_cntSettings3;
extern lv_obj_t * ui_lblReverse;
void ui_event_swReverseColor(lv_event_t * e);
extern lv_obj_t * ui_swReverseColor;
extern lv_obj_t * ui_sliderBrightness;
extern lv_obj_t * ui_swBluetooth;
void ui_event_swBluetooth(lv_event_t * e);
extern lv_obj_t * ui_swKeyboardTab;
extern lv_obj_t * ui_dropdownHidOs;
extern lv_obj_t * ui_cntSettingsBottom;
void ui_event_btnSettingsClose(lv_event_t * e);
extern lv_obj_t * ui_btnSettingsClose;
void ui_event_lblSettingsClose(lv_event_t * e);
extern lv_obj_t * ui_lblSettingsClose;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
