// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnWidgetClicked(lv_event_t * e);
void OnWidgetLongPressed(lv_event_t * e);
void OnMacrosClicked(lv_event_t * e);
void OnWifiChangeState(lv_event_t * e);
void OnWifiScan(lv_event_t * e);
void OnScreenRotateChange(lv_event_t * e);
void OnCardSizeChange(lv_event_t * e);
void OnReverseColorSwitchChange(lv_event_t * e);
void OnBrightnessChange(lv_event_t * e);
void OnSettingsClose(lv_event_t * e);
void OnProfileBtnClicked(lv_event_t * e);
void OnVirtualKeyboardEvent(lv_event_t * e);
void ui_event_swKeyboardTab(lv_event_t * e);
void ui_event_dropdownHidOs(lv_event_t * e);

#ifdef __cplusplus
}
#endif

#endif
