// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// Theme column order:                        Light     Dark      Ocean     Warm      RealBlack
// Real Black (OLED-friendly): pure 0x000000 background; separation uses
// subtle grey borders rather than panel tinting, so the display turns
// OFF pixels for true blacks and saves power on OLED / low-backlight LCDs.

// ── Screen background ─────────────────────────────────────────────────────────
const ui_theme_variable_t _ui_theme_color_background[5] = {0xE5E5E5, 0x353232, 0x0D2137, 0xFFF8E7, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_background[5] = {255,      255,      255,      255,      255};

// Real-black panels: also 0x000000; separation from screen bg comes from
// the widgetBorder colour, not a different fill.
const ui_theme_variable_t _ui_theme_color_panelBackground[5] = {0xFFFFFF, 0x3D2A2A, 0x1B3A5C, 0xFFECB3, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_panelBackground[5] = {255,      255,      255,      255,      255};

// ── Text ──────────────────────────────────────────────────────────────────────
const ui_theme_variable_t _ui_theme_color_text[5] = {0x535353, 0xC0BCBC, 0x87CEEB, 0x5D4037, 0xE0E0E0};
const ui_theme_variable_t _ui_theme_alpha_text[5] = {255,      255,      255,      255,      255};

// ── Buttons ───────────────────────────────────────────────────────────────────
const ui_theme_variable_t _ui_theme_color_button[5] = {0x218CFE, 0x218CFE, 0x00BCD4, 0xFF6F00, 0x1E1E1E};
const ui_theme_variable_t _ui_theme_alpha_button[5] = {255,      255,      255,      255,      255};

const ui_theme_variable_t _ui_theme_color_disabled_button[5] = {0x4E4D4D, 0x4E4D4D, 0x374F5C, 0x9E7A50, 0x0A0A0A};
const ui_theme_variable_t _ui_theme_alpha_disabled_button[5] = {255,      255,      255,      255,      255};

const ui_theme_variable_t _ui_theme_color_pressed_button[5] = {0x0758B1, 0x0758B1, 0x00838F, 0xBF360C, 0x2A2A2A};
const ui_theme_variable_t _ui_theme_alpha_pressed_button[5] = {255,      255,      255,      255,      255};

// ── Button text ───────────────────────────────────────────────────────────────
const ui_theme_variable_t _ui_theme_color_buttonText[5] = {0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xE0E0E0};
const ui_theme_variable_t _ui_theme_alpha_buttonText[5] = {255,      255,      255,      255,      255};

const ui_theme_variable_t _ui_theme_color_pressed_buttonText[5] = {0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_pressed_buttonText[5] = {255,      255,      255,      255,      255};

const ui_theme_variable_t _ui_theme_color_disabled_buttonText[5] = {0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x707070};
const ui_theme_variable_t _ui_theme_alpha_disabled_buttonText[5] = {255,      255,      255,      255,      255};

// ── Accent (widget title/caption text) ────────────────────────────────────────
const ui_theme_variable_t _ui_theme_color_accent[5] = {0x212BD5, 0x5B9EFF, 0x00E5FF, 0xBF360C, 0x4DB6FF};
const ui_theme_variable_t _ui_theme_alpha_accent[5] = {255,      255,      255,      255,      255};

// ── Widget card ───────────────────────────────────────────────────────────────
// Real Black: noticeable grey border separates widgets/panels from the 0x000000
// fill so regions are still clear on an all-black canvas.
const ui_theme_variable_t _ui_theme_color_widgetBorder[5] = {0x838383, 0x555555, 0x1E4D6B, 0xFFCC80, 0x3A3A3A};
const ui_theme_variable_t _ui_theme_alpha_widgetBorder[5] = {255,      255,      255,      255,      255};

// Widget bg is ~1 step lighter than the screen bg in every theme, so cards
// visibly lift off the background. Kept fully opaque (255) — alpha blending
// costs CPU per pixel on ESP32's DMA path, and a lighter opaque shade
// achieves the same visual depth for free.
//                                                Light    Dark     Ocean    Warm     RealBlack
const ui_theme_variable_t _ui_theme_color_widgetBg[5] = {0xF5F5F5, 0x474444, 0x163551, 0xFFFDF5, 0x141414};
const ui_theme_variable_t _ui_theme_alpha_widgetBg[5] = {255,      255,      255,      255,      255};

// ── Active tab border ─────────────────────────────────────────────────────────
// Real Black: subtle grey matches widgetBorder so all separators are
// consistent; the bg color shift (panel 0x000000 → button 0x1E1E1E) is
// already enough contrast to flag the selected tab on OLED.
const ui_theme_variable_t _ui_theme_color_tabBorder[5] = {0x1448A3, 0x1448A3, 0x00BCD4, 0xFF6F00, 0x5A5A5A};
const ui_theme_variable_t _ui_theme_alpha_tabBorder[5] = {255,      255,      255,      255,      255};

// ── Error state (widget bottom border on fetch failure) ───────────────────────
const ui_theme_variable_t _ui_theme_color_error[5] = {0xFF3333, 0xFF5252, 0xFF5252, 0xD32F2F, 0xFF4040};
const ui_theme_variable_t _ui_theme_alpha_error[5] = {255,      255,      255,      255,      255};

uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}
