// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BUTTON 0
#define UI_THEME_COLOR_BACKGROUND 1
#define UI_THEME_COLOR_PANELBACKGROUND 2
#define UI_THEME_COLOR_TEXT 3
#define UI_THEME_COLOR_BUTTONTEXT 4

#define UI_THEME_DEFAULT    0
#define UI_THEME_DARK       1
#define UI_THEME_OCEAN      2
#define UI_THEME_WARM       3
#define UI_THEME_REAL_BLACK 4
#define UI_THEME_COUNT      5

extern const ui_theme_variable_t _ui_theme_color_background[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_background[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_panelBackground[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_panelBackground[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_text[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_text[UI_THEME_COUNT];

/**
 *
*/

extern const ui_theme_variable_t _ui_theme_color_button[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_button[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_disabled_button[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_disabled_button[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_pressed_button[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_pressed_button[UI_THEME_COUNT];

/**
 *
*/

extern const ui_theme_variable_t _ui_theme_color_buttonText[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_buttonText[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_pressed_buttonText[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_pressed_buttonText[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_disabled_buttonText[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_disabled_buttonText[UI_THEME_COUNT];

/**
 * Accent — widget titles, arc caption
 * Each theme: [light, dark, ocean, warm]
 */
extern const ui_theme_variable_t _ui_theme_color_accent[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_accent[UI_THEME_COUNT];

/**
 * Widget card — border and background
 */
extern const ui_theme_variable_t _ui_theme_color_widgetBorder[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_widgetBorder[UI_THEME_COUNT];

extern const ui_theme_variable_t _ui_theme_color_widgetBg[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_widgetBg[UI_THEME_COUNT];

/**
 * Active tab indicator border
 */
extern const ui_theme_variable_t _ui_theme_color_tabBorder[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_tabBorder[UI_THEME_COUNT];

/**
 * Error state — widget bottom border on data fetch failure
 */
extern const ui_theme_variable_t _ui_theme_color_error[UI_THEME_COUNT];
extern const ui_theme_variable_t _ui_theme_alpha_error[UI_THEME_COUNT];

extern const uint32_t * ui_theme_colors[UI_THEME_COUNT];
extern const uint8_t * ui_theme_alphas[UI_THEME_COUNT];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
