// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_ACTIONBUTTON_H
#define _UI_COMP_ACTIONBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT actionButton
#define UI_COMP_ACTIONBUTTON_ACTIONBUTTON 0
#define UI_COMP_ACTIONBUTTON_ACTIONBUTTONLABEL 1
#define _UI_COMP_ACTIONBUTTON_NUM 2
lv_obj_t * ui_actionButton_create(lv_obj_t * comp_parent);
void ui_event_comp_actionButton_actionButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
