// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_actionButton_actionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    lv_obj_t ** comp_actionButton = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnMacrosClicked(e);
    }
}

// COMPONENT actionButton

lv_obj_t * ui_actionButton_create(lv_obj_t * comp_parent)
{
    lv_obj_t * cui_actionButton;
    cui_actionButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_actionButton, 70);
    lv_obj_set_height(cui_actionButton, 70);
    lv_obj_add_flag(cui_actionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_actionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_actionButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // BG
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    // BG gradient
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                            _ui_theme_color_pressed_button);
    lv_obj_set_style_bg_main_stop(cui_actionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_actionButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_actionButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Shadow
    lv_obj_set_style_shadow_color(cui_actionButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_actionButton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_actionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_actionButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_actionButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_actionButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Text color
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_buttonText);
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_buttonText);

    // Pressed BG
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                            _ui_theme_color_pressed_button);
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                            _ui_theme_alpha_pressed_button);

    // Pressed other
    lv_obj_set_style_outline_color(cui_actionButton, lv_color_hex(0x0758B1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(cui_actionButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(cui_actionButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(cui_actionButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(cui_actionButton, lv_color_hex(0x0758B1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(cui_actionButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);                                   

    // Disabled BG
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_COLOR,
                                            _ui_theme_color_disabled_button);
    ui_object_set_themeable_style_property(cui_actionButton, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_OPA,
                                            _ui_theme_alpha_disabled_button);


    lv_obj_t * cui_actionLabel;
    cui_actionLabel = lv_label_create(cui_actionButton);
    lv_obj_set_width(cui_actionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_actionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_actionLabel, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(cui_actionLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_buttonText);
    ui_object_set_themeable_style_property(cui_actionLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,   _ui_theme_alpha_buttonText);
    lv_label_set_text(cui_actionLabel, "-");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ACTIONBUTTON_NUM);
    children[UI_COMP_ACTIONBUTTON_ACTIONBUTTON] = cui_actionButton;
    children[UI_COMP_ACTIONBUTTON_ACTIONBUTTONLABEL] = cui_actionLabel;
    lv_obj_add_event_cb(cui_actionButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_actionButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_actionButton, ui_event_comp_actionButton_actionButton, LV_EVENT_ALL, children);
    ui_comp_actionButton_create_hook(cui_actionButton);

    return cui_actionButton;
}

