// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_WIDGETTEXT_H
#define _UI_COMP_WIDGETTEXT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT widgetText
#define UI_COMP_WIDGET_TEXT_PANEL 0
#define UI_COMP_WIDGET_TEXT_TITLE 1
#define UI_COMP_WIDGET_TEXT_CONTENT 2

#define _UI_COMP_WIDGET_TEXT_NUM 3

lv_obj_t * ui_widgetText_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
