// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_button_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    lv_obj_t ** comp_button = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        // OnButtonClicked(e);
    }
}

// COMPONENT button

lv_obj_t * ui_button_create(lv_obj_t * comp_parent)
{
    // BUTTON
    lv_obj_t * cui_button;
    cui_button = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_button, 100);
    lv_obj_set_height(cui_button, 35);
    lv_obj_add_flag(cui_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_radius(cui_button, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // BG
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    // Text
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_buttonText);
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_buttonText);

    // Pressed BG
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                            _ui_theme_color_pressed_button);
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                            _ui_theme_alpha_pressed_button);

    // Disabled BG
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_COLOR,
                                            _ui_theme_color_disabled_button);
    ui_object_set_themeable_style_property(cui_button, LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_OPA,
                                            _ui_theme_alpha_disabled_button);


    // LABEL
    lv_obj_t * cui_buttonLabel;
    cui_buttonLabel = lv_label_create(cui_button);
    lv_obj_set_width(cui_buttonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_buttonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_buttonLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(cui_buttonLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(cui_buttonLabel, "-");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_NUM);
    children[UI_COMP_BUTTON_BUTTON] = cui_button;
    children[UI_COMP_BUTTON_LABEL] = cui_buttonLabel;
    lv_obj_add_event_cb(cui_button, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_button, del_component_child_event_cb, LV_EVENT_DELETE, children);
    // lv_obj_add_event_cb(cui_button, ui_event_comp_button_button, LV_EVENT_ALL, children);
    ui_comp_button_create_hook(cui_button);

    return cui_button;
}

