/**
 * Shared icon helpers — dedupe, preview URL, upload, reoptimize.
 *
 * Used by MacroEditorPage, SettingsPage, SceneEditorPage, MacrosPage,
 * WidgetsPage. Extracted here so the upload/resize/dedup flow stays
 * consistent across the UI and changes land in one place.
 *
 * Conventions:
 *   * "Base" icon name: "<name>.bin" — display key referenced by macro
 *     configs and the SPA (legacy). Physical files on the device are
 *     the _s/_m/_l size variants PLUS the original compressed source
 *     at /icons/src/<base>.bin (server falls back across image exts).
 *   * Variant filenames: "<stem>_<s|m|l>.bin" — read by the device at
 *     render time. Generated by iconToLvglBin(raw, targetDim).
 *   * Source file: original PNG/JPG/SVG/WEBP uploaded as-is → ~8x SD
 *     space saving vs 256×256 ARGB8888 .bin, and lossless regenerate.
 */
import { Api, loadBaseUrl } from '../api/http';
import { iconToLvglBin, lvglBinToDataUrl, resizeLvglBin } from './image';

/** Variant filename for a size keyed off the .bin display name. */
export function iconVariantName(baseName: string, sz: 's' | 'm' | 'l'): string {
  const stem = baseName.endsWith('.bin') ? baseName.slice(0, -4) : baseName;
  return `${stem}_${sz}.bin`;
}

/**
 * Deduplicate raw /api/icons response into a gallery-friendly list:
 *   * groups "play_s.bin" / "play_m.bin" / "play_l.bin" under "play.bin"
 *   * keeps legacy single-file icons ("play.bin" with no size suffix) as-is
 *
 * Returns the display list + a preview map that points each display name
 * at the actual file used for the thumbnail (_m variant for new icons,
 * self for legacy).
 */
export function dedupeIconList(all: string[]): {
  items: string[];
  previewMap: Record<string, string>;
} {
  const previewMap: Record<string, string> = {};
  const seen = new Set<string>();
  const items: string[] = [];
  for (const n of all) {
    if (n.endsWith('_m.bin')) {
      const base = n.slice(0, -6) + '.bin';
      if (!seen.has(base)) {
        seen.add(base);
        items.push(base);
        previewMap[base] = n;
      }
    } else if (n.endsWith('.bin') && !/_[sml]\.bin$/.test(n)) {
      if (!seen.has(n)) {
        seen.add(n);
        items.push(n);
        previewMap[n] = n;
      }
    }
  }
  return { items, previewMap };
}

/**
 * Default preview URL: the compressed source under /icons/src/<name>.
 * The device falls back across .png/.jpg/.svg/.webp/.gif for the .bin
 * compat key, so <img src=...> decodes natively in the browser.
 */
export function iconPreviewUrl(name: string): string {
  const base = loadBaseUrl();
  return `${base}/icons/src/${name}`;
}

/**
 * Populate a {name → preview-url} map. Tries /icons/src/<name> first
 * (native <img> decode). Only when the source is absent or not served
 * as an image does it fall back to decoding the _m .bin via
 * lvglBinToDataUrl. Never throws — any single preview failure is
 * swallowed so the gallery list itself keeps rendering.
 */
export async function buildIconPreviewMap(
  names: string[],
  previewMap: Record<string, string>,
): Promise<Record<string, string>> {
  const base = loadBaseUrl();
  const out: Record<string, string> = {};
  await Promise.all(names.map(async (name) => {
    const srcUrl = `${base}/icons/src/${name}`;
    try {
      const resp = await fetch(srcUrl);
      if (resp.ok) {
        const ct = resp.headers.get('content-type') || '';
        if (ct.startsWith('image/')) { out[name] = srcUrl; return; }
      }
    } catch { /* fall through */ }
    try {
      const previewFile = previewMap[name] ?? iconVariantName(name, 'm');
      out[name] = await lvglBinToDataUrl(`${base}/icons/${previewFile}`);
    } catch { /* leave blank — template uses empty string */ }
  }));
  return out;
}

/** Percent-of-btnSize for the s/m/l variants. Kept here so all call sites
 *  agree on the ratios. */
export const VARIANT_PCTS: Record<'s' | 'm' | 'l', number> = { s: 50, m: 75, l: 100 };

/**
 * Full SPA upload flow: upload the original compressed file as the
 * source then emit 3 display variants at the current btn_size.
 * @returns baseName of the uploaded icon ("<stem>.bin")
 */
export async function uploadIconWithVariants(raw: File, btnSize: number): Promise<string> {
  // Baseline display key stays .bin so every macro/widget reference
  // works regardless of the stored source's real extension.
  const baseName = raw.name.replace(/\.[^.]+$/, '') + '.bin';
  await Api.uploadIconSrc(raw);
  for (const [sz, pct] of Object.entries(VARIANT_PCTS) as ['s' | 'm' | 'l', number][]) {
    const targetDim = Math.max(8, Math.round(btnSize * pct / 100));
    const variantFile = await iconToLvglBin(raw, targetDim);
    const variantName = iconVariantName(baseName, sz);
    const renamed = new File([variantFile], variantName, { type: variantFile.type });
    await Api.uploadIcon(renamed);
  }
  return baseName;
}

/**
 * Re-generate display variants for a set of icons, pulling the source
 * from the device and re-encoding per current btn_size. Progress
 * callback fires before each icon so the UI can show a progress bar.
 * Silently skips icons whose source is missing.
 */
export async function reoptimizeIcons(
  usedIcons: string[],
  btnSize: number,
  onProgress?: (done: number, total: number) => void,
): Promise<void> {
  // Only process icons that still have a variant on SD
  const allIcons = await Api.getIcons();
  const toProcess = usedIcons.filter(name => {
    const base = name.endsWith('.bin') ? name.slice(0, -4) : name;
    return allIcons.includes(base + '_m.bin');
  });
  for (let i = 0; i < toProcess.length; i++) {
    onProgress?.(i, toProcess.length);
    const iconName = toProcess[i];
    const base = iconName.endsWith('.bin') ? iconName.slice(0, -4) : iconName;
    const srcUrl = Api.getIconSrcUrl(base + '.bin');
    for (const [sz, pct] of Object.entries(VARIANT_PCTS) as ['s' | 'm' | 'l', number][]) {
      const dim = Math.max(8, Math.round(btnSize * pct / 100));
      const file = await resizeLvglBin(srcUrl, dim, `${base}_${sz}.bin`);
      if (file) await Api.uploadIcon(file);
    }
  }
  onProgress?.(toProcess.length, toProcess.length);
}
