import type { Widget } from '../stores/widgets';

export interface WidgetTemplate {
  name: string;
  description: string;
  category: string;
  icon: string;
  widget: Omit<Widget, 'id'>;
}

export const WIDGET_TEMPLATES: WidgetTemplate[] = [
  // ── Network ──────────────────────────────────────────────────────────────
  {
    name: 'Public IP',
    description: 'Shows your current public IP address',
    category: 'Network',
    icon: '🌐',
    widget: {
      title: 'My IP',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.myip.com',
      parse_type: 'json',
      json_keys: ['ip'],
      template: '{ip}',
      update: 60,
    },
  },
  {
    name: 'World Time',
    description: 'Current UTC date/time from timeapi.io',
    category: 'Network',
    icon: '🕐',
    widget: {
      title: 'UTC Time',
      type: 'text',
      data_target: 'url_system',
      url: 'https://timeapi.io/api/v1/time/current/utc',
      parse_type: 'json',
      json_keys: ['utc_time'],
      template: '{utc_time}',
      update: 30,
    },
  },

  // ── Home Assistant ────────────────────────────────────────────────────────
  {
    name: 'HA Sensor (text)',
    description: 'Any Home Assistant sensor as a text value',
    category: 'Home Assistant',
    icon: '🏠',
    widget: {
      title: 'HA Sensor',
      type: 'text',
      data_target: 'url_system',
      url: 'http://homeassistant.local:8123/api/states/sensor.YOUR_SENSOR',
      parse_type: 'json',
      json_keys: ['state'],
      template: '{state}',
      update: 30,
      headers: [{ key: 'Authorization', value: 'Bearer YOUR_LONG_LIVED_TOKEN' }],
    },
  },
  {
    name: 'HA Sensor + unit (text)',
    description: 'Sensor value with unit_of_measurement attribute',
    category: 'Home Assistant',
    icon: '🏠',
    widget: {
      title: 'HA Sensor',
      type: 'text',
      data_target: 'url_system',
      url: 'http://homeassistant.local:8123/api/states/sensor.YOUR_SENSOR',
      parse_type: 'json',
      json_keys: ['state', 'attributes.unit_of_measurement'],
      template: '{state} {attributes.unit_of_measurement}',
      update: 30,
      headers: [{ key: 'Authorization', value: 'Bearer YOUR_LONG_LIVED_TOKEN' }],
    },
  },
  {
    name: 'HA Progress bar',
    description: 'Numeric sensor (0–100) as horizontal progress bar',
    category: 'Home Assistant',
    icon: '📊',
    widget: {
      title: 'HA Progress',
      type: 'progress',
      style: 0,
      data_target: 'url_system',
      url: 'http://homeassistant.local:8123/api/states/sensor.YOUR_SENSOR',
      parse_type: 'json',
      json_keys: ['state'],
      template: '{state}',
      update: 30,
      headers: [{ key: 'Authorization', value: 'Bearer YOUR_LONG_LIVED_TOKEN' }],
    },
  },
  {
    name: 'HA Arc gauge',
    description: 'Numeric sensor (0–100) as an arc gauge',
    category: 'Home Assistant',
    icon: '🔵',
    widget: {
      title: 'HA Arc',
      type: 'progress',
      style: 2,
      data_target: 'url_system',
      url: 'http://homeassistant.local:8123/api/states/sensor.YOUR_SENSOR',
      parse_type: 'json',
      json_keys: ['state'],
      template: '{state}',
      update: 30,
      headers: [{ key: 'Authorization', value: 'Bearer YOUR_LONG_LIVED_TOKEN' }],
    },
  },
  {
    name: 'HA CPU Usage',
    description: 'Home Assistant host CPU % as arc gauge (requires systemmonitor integration)',
    category: 'Home Assistant',
    icon: '💻',
    widget: {
      title: 'CPU',
      type: 'progress',
      style: 2,
      data_target: 'url_system',
      url: 'http://homeassistant.local:8123/api/states/sensor.processor_use',
      parse_type: 'json',
      json_keys: ['state'],
      template: '{state}',
      update: 10,
      headers: [{ key: 'Authorization', value: 'Bearer YOUR_LONG_LIVED_TOKEN' }],
    },
  },
  {
    name: 'HA RAM Usage',
    description: 'Home Assistant host RAM % as horizontal bar (requires systemmonitor integration)',
    category: 'Home Assistant',
    icon: '🧠',
    widget: {
      title: 'RAM',
      type: 'progress',
      style: 0,
      data_target: 'url_system',
      url: 'http://homeassistant.local:8123/api/states/sensor.memory_use_percent',
      parse_type: 'json',
      json_keys: ['state'],
      template: '{state}',
      update: 10,
      headers: [{ key: 'Authorization', value: 'Bearer YOUR_LONG_LIVED_TOKEN' }],
    },
  },

  // ── System (companion) ──────────────────────────────────────────────────
  {
    name: 'CPU Usage',
    description: 'PC CPU usage % from CYD Companion',
    category: 'System',
    icon: '💻',
    widget: {
      title: 'CPU',
      type: 'progress',
      style: 2,
      data_target: 'system',
      metric_id: 'cpu_usage',
      template: '{value}',
      update: 5,
    },
  },
  {
    name: 'RAM Usage',
    description: 'PC RAM usage % from CYD Companion',
    category: 'System',
    icon: '🧠',
    widget: {
      title: 'RAM',
      type: 'progress',
      style: 0,
      data_target: 'system',
      metric_id: 'ram_usage',
      template: '{value}',
      update: 5,
    },
  },
  {
    name: 'Disk Usage',
    description: 'PC disk usage % from CYD Companion',
    category: 'System',
    icon: '💾',
    widget: {
      title: 'Disk',
      type: 'progress',
      style: 0,
      data_target: 'system',
      metric_id: 'disk_usage',
      template: '{value}',
      update: 30,
    },
  },

  // ── Weather ─────────────────────────────────────────────────────────────
  {
    name: 'Current Temperature',
    description: 'Current temperature from Open-Meteo (no API key, edit lat/lon)',
    category: 'Weather',
    icon: '🌡️',
    widget: {
      title: 'Temp',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current_weather=true',
      parse_type: 'json',
      json_keys: ['current_weather.temperature'],
      template: '{current_weather.temperature}°C',
      update: 300,
    },
  },
  {
    name: 'Weather Code',
    description: 'WMO weather code from Open-Meteo (sunny/cloudy/rain)',
    category: 'Weather',
    icon: '⛅',
    widget: {
      title: 'Weather',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current_weather=true',
      parse_type: 'json',
      json_keys: ['current_weather.temperature', 'current_weather.weathercode'],
      template: '{current_weather.temperature}°C (code: {current_weather.weathercode})',
      update: 300,
    },
  },

  // ── Crypto ──────────────────────────────────────────────────────────────
  {
    name: 'BTC Price',
    description: 'Bitcoin price in USD from CoinGecko (no API key)',
    category: 'Crypto',
    icon: '₿',
    widget: {
      title: 'BTC',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd',
      parse_type: 'json',
      json_keys: ['bitcoin.usd'],
      template: '${bitcoin.usd}',
      update: 60,
    },
  },
  {
    name: 'ETH Price',
    description: 'Ethereum price in USD from CoinGecko (no API key)',
    category: 'Crypto',
    icon: 'Ξ',
    widget: {
      title: 'ETH',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd',
      parse_type: 'json',
      json_keys: ['ethereum.usd'],
      template: '${ethereum.usd}',
      update: 60,
    },
  },

  // ── Network (companion) ─────────────────────────────────────────────────
  {
    name: 'Ping Monitor',
    description: 'Network ping from CYD Companion',
    category: 'Network',
    icon: '📡',
    widget: {
      title: 'Ping',
      type: 'text',
      data_target: 'system',
      metric_id: 'ping_ms',
      template: '{value} ms',
      update: 10,
    },
  },

  // ── Weather (extended) ───────────────────────────────────────────────────
  {
    name: 'Humidity',
    description: 'Relative humidity % from Open-Meteo (edit lat/lon)',
    category: 'Weather',
    icon: '💧',
    widget: {
      title: 'Humidity',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current=relative_humidity_2m',
      parse_type: 'json',
      json_keys: ['current.relative_humidity_2m'],
      template: '{current.relative_humidity_2m}%',
      update: 300,
    },
  },
  {
    name: 'Feels Like',
    description: 'Apparent temperature from Open-Meteo (edit lat/lon)',
    category: 'Weather',
    icon: '🌡️',
    widget: {
      title: 'Feels Like',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current=apparent_temperature',
      parse_type: 'json',
      json_keys: ['current.apparent_temperature'],
      template: '{current.apparent_temperature}°C',
      update: 300,
    },
  },
  {
    name: 'Wind Speed',
    description: 'Wind speed km/h from Open-Meteo (edit lat/lon)',
    category: 'Weather',
    icon: '💨',
    widget: {
      title: 'Wind',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current=wind_speed_10m',
      parse_type: 'json',
      json_keys: ['current.wind_speed_10m'],
      template: '{current.wind_speed_10m} km/h',
      update: 300,
    },
  },
  {
    name: 'UV Index',
    description: 'UV radiation index from Open-Meteo (edit lat/lon)',
    category: 'Weather',
    icon: '☀️',
    widget: {
      title: 'UV Index',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current=uv_index',
      parse_type: 'json',
      json_keys: ['current.uv_index'],
      template: 'UV {current.uv_index}',
      update: 600,
    },
  },

  // ── Air Quality ──────────────────────────────────────────────────────────
  {
    name: 'PM2.5',
    description: 'Fine particle pollution from Open-Meteo (edit lat/lon, no API key)',
    category: 'Air Quality',
    icon: '🌫️',
    widget: {
      title: 'PM2.5',
      type: 'text',
      data_target: 'url_system',
      url: 'https://air-quality-api.open-meteo.com/v1/air-quality?latitude=50.45&longitude=30.52&current=pm2_5',
      parse_type: 'json',
      json_keys: ['current.pm2_5'],
      template: 'PM2.5: {current.pm2_5}',
      update: 600,
    },
  },
  {
    name: 'European AQI',
    description: 'European Air Quality Index from Open-Meteo (edit lat/lon, no API key)',
    category: 'Air Quality',
    icon: '🍃',
    widget: {
      title: 'AQI',
      type: 'text',
      data_target: 'url_system',
      url: 'https://air-quality-api.open-meteo.com/v1/air-quality?latitude=50.45&longitude=30.52&current=european_aqi',
      parse_type: 'json',
      json_keys: ['current.european_aqi'],
      template: 'AQI: {current.european_aqi}',
      update: 600,
    },
  },

  // ── Currency ─────────────────────────────────────────────────────────────
  {
    name: 'USD → EUR',
    description: 'USD to EUR exchange rate (open.er-api.com, no API key)',
    category: 'Currency',
    icon: '💱',
    widget: {
      title: 'USD/EUR',
      type: 'text',
      data_target: 'url_system',
      url: 'https://open.er-api.com/v6/latest/USD',
      parse_type: 'json',
      json_keys: ['rates.EUR'],
      template: 'EUR {rates.EUR}',
      update: 3600,
    },
  },
  {
    name: 'USD → UAH',
    description: 'USD to UAH exchange rate (open.er-api.com, no API key)',
    category: 'Currency',
    icon: '💱',
    widget: {
      title: 'USD/UAH',
      type: 'text',
      data_target: 'url_system',
      url: 'https://open.er-api.com/v6/latest/USD',
      parse_type: 'json',
      json_keys: ['rates.UAH'],
      template: 'UAH {rates.UAH}',
      update: 3600,
    },
  },
  {
    name: 'EUR → UAH',
    description: 'EUR to UAH exchange rate (open.er-api.com, no API key)',
    category: 'Currency',
    icon: '💱',
    widget: {
      title: 'EUR/UAH',
      type: 'text',
      data_target: 'url_system',
      url: 'https://open.er-api.com/v6/latest/EUR',
      parse_type: 'json',
      json_keys: ['rates.UAH'],
      template: 'UAH {rates.UAH}',
      update: 3600,
    },
  },

  // ── Crypto (extended) ────────────────────────────────────────────────────
  {
    name: 'SOL Price',
    description: 'Solana price in USD from CoinGecko (no API key)',
    category: 'Crypto',
    icon: '◎',
    widget: {
      title: 'SOL',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd',
      parse_type: 'json',
      json_keys: ['solana.usd'],
      template: '${solana.usd}',
      update: 60,
    },
  },

  // ── GitHub ───────────────────────────────────────────────────────────────
  {
    name: 'GitHub Stars',
    description: 'Star count for any public repo — replace {owner}/{repo} in URL',
    category: 'GitHub',
    icon: '⭐',
    widget: {
      title: 'Stars',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.github.com/repos/{owner}/{repo}',
      parse_type: 'json',
      json_keys: ['stargazers_count'],
      template: 'Stars: {stargazers_count}',
      update: 3600,
    },
  },
  {
    name: 'GitHub Issues',
    description: 'Open issue count for any public repo — replace {owner}/{repo} in URL',
    category: 'GitHub',
    icon: '🐛',
    widget: {
      title: 'Issues',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.github.com/repos/{owner}/{repo}',
      parse_type: 'json',
      json_keys: ['open_issues_count'],
      template: 'Issues: {open_issues_count}',
      update: 3600,
    },
  },
  {
    name: 'GitHub Latest Release',
    description: 'Latest release tag for any public repo — replace {owner}/{repo} in URL',
    category: 'GitHub',
    icon: '🚀',
    widget: {
      title: 'Release',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.github.com/repos/{owner}/{repo}/releases/latest',
      parse_type: 'json',
      json_keys: ['tag_name'],
      template: '{tag_name}',
      update: 3600,
    },
  },

  // ── Astronomy ────────────────────────────────────────────────────────────
  {
    name: 'Sunrise',
    description: 'Today\'s sunrise time UTC (edit lat/lon)',
    category: 'Astronomy',
    icon: '🌅',
    widget: {
      title: 'Sunrise',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.sunrise-sunset.org/json?lat=50.45&lng=30.52&formatted=0',
      parse_type: 'json',
      json_keys: ['results.sunrise'],
      template: 'Rise: {results.sunrise}',
      update: 86400,
    },
  },
  {
    name: 'Sunset',
    description: 'Today\'s sunset time UTC (edit lat/lon)',
    category: 'Astronomy',
    icon: '🌇',
    widget: {
      title: 'Sunset',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.sunrise-sunset.org/json?lat=50.45&lng=30.52&formatted=0',
      parse_type: 'json',
      json_keys: ['results.sunset'],
      template: 'Set: {results.sunset}',
      update: 86400,
    },
  },

  // ── Space ────────────────────────────────────────────────────────────────
  {
    name: 'ISS Latitude',
    description: 'Current ISS latitude from open-notify.org (HTTP, no API key)',
    category: 'Space',
    icon: '🛰️',
    widget: {
      title: 'ISS Lat',
      type: 'text',
      data_target: 'url',
      url: 'http://api.open-notify.org/iss-now.json',
      parse_type: 'json',
      json_keys: ['iss_position.latitude'],
      template: 'Lat {iss_position.latitude}',
      update: 10,
    },
  },
  {
    name: 'ISS Longitude',
    description: 'Current ISS longitude from open-notify.org (HTTP, no API key)',
    category: 'Space',
    icon: '🛰️',
    widget: {
      title: 'ISS Lon',
      type: 'text',
      data_target: 'url',
      url: 'http://api.open-notify.org/iss-now.json',
      parse_type: 'json',
      json_keys: ['iss_position.longitude'],
      template: 'Lon {iss_position.longitude}',
      update: 10,
    },
  },
  {
    name: 'People in Space',
    description: 'Number of humans currently in space (open-notify.org, HTTP)',
    category: 'Space',
    icon: '👨‍🚀',
    widget: {
      title: 'In Space',
      type: 'text',
      data_target: 'url',
      url: 'http://api.open-notify.org/astros.json',
      parse_type: 'json',
      json_keys: ['number'],
      template: '{number} in space',
      update: 3600,
    },
  },

  // ── Services Status ──────────────────────────────────────────────────────
  {
    name: 'GitHub Status',
    description: 'GitHub platform operational status',
    category: 'Services',
    icon: '🟢',
    widget: {
      title: 'GitHub',
      type: 'text',
      data_target: 'url_system',
      url: 'https://www.githubstatus.com/api/v2/status.json',
      parse_type: 'json',
      json_keys: ['status.description'],
      template: 'GH: {status.description}',
      update: 300,
    },
  },

  // ── Fun & Misc ───────────────────────────────────────────────────────────
  {
    name: 'Random Quote',
    description: 'Random inspirational quote (dummyjson.com, no API key)',
    category: 'Fun & Misc',
    icon: '💬',
    widget: {
      title: 'Quote',
      type: 'text',
      data_target: 'url_system',
      url: 'https://dummyjson.com/quotes/random',
      parse_type: 'json',
      json_keys: ['quote', 'author'],
      template: '{quote} - {author}',
      update: 3600,
    },
  },
  {
    name: 'Programming Joke',
    description: 'Random programming joke (jokeapi.dev, no API key)',
    category: 'Fun & Misc',
    icon: '😄',
    widget: {
      title: 'Dev Joke',
      type: 'text',
      data_target: 'url_system',
      url: 'https://v2.jokeapi.dev/joke/Programming?type=single',
      parse_type: 'json',
      json_keys: ['joke'],
      template: '{joke}',
      update: 3600,
    },
  },
  {
    name: 'Any Joke',
    description: 'Random joke of any category (jokeapi.dev, no API key)',
    category: 'Fun & Misc',
    icon: '🤣',
    widget: {
      title: 'Joke',
      type: 'text',
      data_target: 'url_system',
      url: 'https://v2.jokeapi.dev/joke/Any?type=single',
      parse_type: 'json',
      json_keys: ['joke'],
      template: '{joke}',
      update: 3600,
    },
  },
  {
    name: 'Dad Joke',
    description: 'Random dad joke (icanhazdadjoke.com, requires Accept header)',
    category: 'Fun & Misc',
    icon: '👨',
    widget: {
      title: 'Dad Joke',
      type: 'text',
      data_target: 'url_system',
      url: 'https://icanhazdadjoke.com/',
      parse_type: 'json',
      json_keys: ['joke'],
      template: '{joke}',
      update: 3600,
      headers: [{ key: 'Accept', value: 'application/json' }],
    },
  },
  {
    name: 'Useless Fact',
    description: 'Random useless fact (uselessfacts.jsph.pl, no API key)',
    category: 'Fun & Misc',
    icon: '🧠',
    widget: {
      title: 'Fact',
      type: 'text',
      data_target: 'url_system',
      url: 'https://uselessfacts.jsph.pl/api/v2/facts/random',
      parse_type: 'json',
      json_keys: ['text'],
      template: '{text}',
      update: 3600,
    },
  },
  {
    name: 'Cat Fact',
    description: 'Random cat fact (catfact.ninja, no API key)',
    category: 'Fun & Misc',
    icon: '🐱',
    widget: {
      title: 'Cat Fact',
      type: 'text',
      data_target: 'url_system',
      url: 'https://catfact.ninja/fact',
      parse_type: 'json',
      json_keys: ['fact'],
      template: '{fact}',
      update: 3600,
    },
  },
  {
    name: 'xkcd Latest',
    description: 'Title and number of the latest xkcd comic',
    category: 'Fun & Misc',
    icon: '🖼️',
    widget: {
      title: 'xkcd',
      type: 'text',
      data_target: 'url_system',
      url: 'https://xkcd.com/info.0.json',
      parse_type: 'json',
      json_keys: ['num', 'title'],
      template: '#{num}: {title}',
      update: 3600,
    },
  },
  {
    name: 'Earthquakes Today',
    description: 'Number of significant earthquakes in the last 24h (USGS)',
    category: 'Fun & Misc',
    icon: '🌍',
    widget: {
      title: 'Quakes',
      type: 'text',
      data_target: 'url_system',
      url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_day.geojson',
      parse_type: 'json',
      json_keys: ['metadata.count'],
      template: 'Quakes today: {metadata.count}',
      update: 3600,
    },
  },

  // ── Word of the Day ──────────────────────────────────────────────────────
  {
    name: 'Word of the Day',
    description: 'Daily word from Wordnik (free API key required — wordnik.com)',
    category: 'Word of the Day',
    icon: '📖',
    widget: {
      title: 'Word',
      type: 'text',
      data_target: 'url_system',
      url: 'https://api.wordnik.com/v4/words.json/wordOfTheDay?api_key=YOUR_API_KEY',
      parse_type: 'json',
      json_keys: ['word'],
      template: '{word}',
      update: 86400,
    },
  },
  {
    name: 'Random Word',
    description: 'Random English word (random-word-api.vercel.app, array key "0")',
    category: 'Word of the Day',
    icon: '🔤',
    widget: {
      title: 'Random Word',
      type: 'text',
      data_target: 'url_system',
      url: 'https://random-word-api.vercel.app/word',
      parse_type: 'json',
      json_keys: ['0'],
      template: '{0}',
      update: 3600,
    },
  },

  // ── Array-enabled templates (require jsonGetPath array fix) ──────────────
  {
    name: 'Next Holiday (UA)',
    description: 'Next public holiday in Ukraine name and date',
    category: 'Fun & Misc',
    icon: '🎉',
    widget: {
      title: 'Next Holiday',
      type: 'text',
      data_target: 'url_system',
      url: 'https://date.nager.at/api/v3/NextPublicHolidays/UA',
      parse_type: 'json',
      json_keys: ['0.name', '0.date'],
      template: '{0.name} · {0.date}',
      update: 86400,
    },
  },
  {
    name: 'Random Cocktail',
    description: 'Random cocktail name from TheCocktailDB (no API key)',
    category: 'Fun & Misc',
    icon: '🍹',
    widget: {
      title: 'Cocktail',
      type: 'text',
      data_target: 'url_system',
      url: 'https://www.thecocktaildb.com/api/json/v1/1/random.php',
      parse_type: 'json',
      json_keys: ['drinks.0.strDrink'],
      template: '{drinks.0.strDrink}',
      update: 3600,
    },
  },
];

export const TEMPLATE_CATEGORIES = [...new Set(WIDGET_TEMPLATES.map(t => t.category))];
