"""
PlatformIO pre-build script — regenerates src/modules/wifi/service_shell.h
and src/version.h from web/shell.html before every firmware build.

Single source of truth: custom_spa_version in platformio.ini [env].
REPO is read from git remote origin URL.

Runs unconditionally at script-load time (pre: prefix in extra_scripts).
"""

import gzip
import re
import subprocess
from pathlib import Path

Import("env")  # noqa: F821  (SCons built-in)

TCP_SND_BUF = 5760  # warn if gzip exceeds this (no-PSRAM single-send limit)


def _git_repo() -> str:
    """Return 'owner/repo' from git remote origin, or fallback."""
    try:
        url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            stderr=subprocess.DEVNULL, text=True
        ).strip()
        # https://github.com/owner/repo.git  or  git@github.com:owner/repo.git
        m = re.search(r'[:/]([^/:]+/[^/]+?)(?:\.git)?$', url)
        return m.group(1) if m else "owner/repo"
    except Exception:
        return "owner/repo"


def _run(env):
    root      = Path(env["PROJECT_DIR"])
    shell_src = root / "web" / "shell.html"
    out_path  = root / "src" / "modules" / "wifi" / "service_shell.h"
    ver_h     = root / "src" / "version.h"

    if not shell_src.exists():
        print(f"[gen_shell_h] WARNING: {shell_src} not found — skipping")
        return

    version = env.GetProjectOption("custom_spa_version", "v0.0.0")
    if not version.startswith("v"):
        version = f"v{version}"

    repo    = _git_repo()
    html    = shell_src.read_text(encoding="utf-8") \
                       .replace("__SPA_VERSION__", version) \
                       .replace("__REPO__", repo)
    raw     = html.encode("utf-8")
    gz      = gzip.compress(raw, compresslevel=9)
    raw_len = len(raw)
    gz_len  = len(gz)

    if gz_len > TCP_SND_BUF:
        print(f"[gen_shell_h] WARNING: service_shell.h gz size {gz_len} B "
              f"exceeds TCP_SND_BUF ({TCP_SND_BUF} B)")

    hex_lines = []
    for i in range(0, gz_len, 16):
        chunk = ", ".join(f"0x{b:02x}" for b in gz[i:i+16])
        hex_lines.append(f"    {chunk}")

    header = (
        "#pragma once\n"
        "// AUTO-GENERATED by scripts/gen_shell_h.py before every firmware build.\n"
        "// DO NOT EDIT — change web/shell.html or platformio.ini [env] custom_spa_version.\n"
        "// Shell HTML served at GET / in service mode on all boards.\n"
        f"// Version: {version}  Raw: {raw_len} B → gzip: {gz_len} B\n"
        "\n"
        "static const uint8_t SERVICE_SHELL_HTML_GZ[] = {\n"
        + ",\n".join(hex_lines) + "\n};\n"
        f"static const size_t SERVICE_SHELL_HTML_GZ_LEN = {gz_len};\n"
    )

    out_path.write_text(header, encoding="utf-8")

    # Keep src/version.h in sync so C++ code can reference SPA_VERSION.
    ver_h.write_text(
        "#pragma once\n"
        "// AUTO-GENERATED by scripts/gen_shell_h.py — do not edit.\n"
        "// Change custom_spa_version in platformio.ini to bump.\n"
        f'#define SPA_VERSION "{version}"\n',
        encoding="utf-8"
    )

    print(f"[gen_shell_h] version={version}  repo={repo}  "
          f"raw={raw_len} B  gz={gz_len} B")


# Run immediately on every pio invocation — no SCons cache bypass needed.
_run(env)  # noqa: F821
