// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screenWifi_screen_init(void)
{
    ui_screenWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_screenWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_screenWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_screenWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_screenWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);

    ui_cntWifi = lv_obj_create(ui_screenWifi);
    lv_obj_remove_style_all(ui_cntWifi);
    lv_obj_set_width(ui_cntWifi, lv_pct(100));
    lv_obj_set_height(ui_cntWifi, lv_pct(100));
    lv_obj_set_align(ui_cntWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cntWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_cntWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cntWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cntWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cntWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cntWifiSettings = lv_obj_create(ui_cntWifi);
    lv_obj_remove_style_all(ui_cntWifiSettings);
    lv_obj_set_width(ui_cntWifiSettings, lv_pct(100));
    lv_obj_set_height(ui_cntWifiSettings, lv_pct(100));
    lv_obj_set_flex_flow(ui_cntWifiSettings, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cntWifiSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cntWifiSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /**
     * WiFi SSID
    */

    ui_cnt1 = lv_obj_create(ui_cntWifiSettings);
    lv_obj_remove_style_all(ui_cnt1);
    lv_obj_set_height(ui_cnt1, 22);
    lv_obj_set_width(ui_cnt1, lv_pct(100));
    lv_obj_set_flex_flow(ui_cnt1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cnt1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cnt1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_cnt1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cnt1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cnt1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cnt1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiSSID = lv_label_create(ui_cnt1);
    lv_obj_set_width(ui_lblWifiSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiSSID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblWifiSSID, "SSID");

    ui_ddWifiSSID = lv_dropdown_create(ui_cnt1);
    lv_dropdown_set_options(ui_ddWifiSSID, "");
    lv_obj_set_width(ui_ddWifiSSID, 150);
    lv_obj_set_height(ui_ddWifiSSID, lv_pct(100));
    lv_obj_set_align(ui_ddWifiSSID, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ddWifiSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    /**
     * Wifi Password
    */

    ui_cnt2 = lv_obj_create(ui_cntWifiSettings);
    lv_obj_remove_style_all(ui_cnt2);
    lv_obj_set_height(ui_cnt2, 22);
    lv_obj_set_width(ui_cnt2, lv_pct(100));
    lv_obj_set_flex_flow(ui_cnt2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cnt2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cnt2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_cnt2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cnt2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cnt2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cnt2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiPass = lv_label_create(ui_cnt2);
    lv_obj_set_width(ui_lblWifiPass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiPass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiPass, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblWifiPass, "Password");

    ui_txtWifiPass = lv_textarea_create(ui_cnt2);
    lv_obj_set_width(ui_txtWifiPass, 150);
    lv_obj_set_height(ui_txtWifiPass, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_txtWifiPass, 150);
    lv_obj_set_y(ui_txtWifiPass, 5);
    lv_obj_set_align(ui_txtWifiPass, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_txtWifiPass, 20);
    lv_textarea_set_one_line(ui_txtWifiPass, true);
    lv_textarea_set_password_mode(ui_txtWifiPass, true);

    /**
     * mDNS Hostname
    */

    ui_cntWifiHostname = lv_obj_create(ui_cntWifiSettings);
    lv_obj_remove_style_all(ui_cntWifiHostname);
    lv_obj_set_height(ui_cntWifiHostname, 22);
    lv_obj_set_width(ui_cntWifiHostname, lv_pct(100));
    lv_obj_set_flex_flow(ui_cntWifiHostname, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cntWifiHostname, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cntWifiHostname, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_left(ui_cntWifiHostname, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cntWifiHostname, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cntWifiHostname, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cntWifiHostname, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiHostname = lv_label_create(ui_cntWifiHostname);
    lv_obj_set_width(ui_lblWifiHostname, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblWifiHostname, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_lblWifiHostname, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblWifiHostname, "mDNS Host");

    ui_txtWifiHostname = lv_textarea_create(ui_cntWifiHostname);
    lv_obj_set_width(ui_txtWifiHostname, 150);
    lv_obj_set_height(ui_txtWifiHostname, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_txtWifiHostname, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_txtWifiHostname, 32);
    lv_textarea_set_one_line(ui_txtWifiHostname, true);
    lv_textarea_set_placeholder_text(ui_txtWifiHostname, "CYD-Dashboard");

    lv_obj_add_event_cb(ui_txtWifiHostname, ui_event_txtWifiHostname, LV_EVENT_ALL, NULL);

    /**
     * Wifi Connect/Disconnect/Scan
    */

    ui_cnt3 = lv_obj_create(ui_cntWifiSettings);
    lv_obj_remove_style_all(ui_cnt3);
    lv_obj_set_height(ui_cnt3, 45);
    lv_obj_set_width(ui_cnt3, lv_pct(100));
    lv_obj_set_x(ui_cnt3, -5);
    lv_obj_set_y(ui_cnt3, 26);
    lv_obj_clear_flag(ui_cnt3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_cnt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cnt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cnt3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cnt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Wifi Connect/Disconnect
    ui_btnWifiAction = ui_button_create(ui_cnt3);
    lv_obj_set_x(ui_btnWifiAction, 0);
    lv_obj_set_y(ui_btnWifiAction, 0);
    lv_obj_set_align(ui_btnWifiAction, LV_ALIGN_LEFT_MID);
    
    ui_lblWifiAction = ui_comp_get_child(ui_btnWifiAction, UI_COMP_BUTTON_LABEL);
    lv_label_set_text(ui_lblWifiAction, "Connect");

    // Wifi Scan Button
    ui_btnWifiScan = ui_button_create(ui_cnt3);
    lv_obj_set_x(ui_btnWifiScan, 0);
    lv_obj_set_y(ui_btnWifiScan, 0);
    lv_obj_set_align(ui_btnWifiScan, LV_ALIGN_RIGHT_MID);

    ui_lblWifiScan = ui_comp_get_child(ui_btnWifiScan, UI_COMP_BUTTON_LABEL);
    lv_label_set_text(ui_lblWifiScan, "Scan");

    /**
     * Other
    */

    ui_cnt4 = lv_obj_create(ui_cntWifiSettings);
    lv_obj_remove_style_all(ui_cnt4);
    lv_obj_set_width(ui_cnt4, lv_pct(100));
    lv_obj_set_height(ui_cnt4, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_cnt4, -5);
    lv_obj_set_y(ui_cnt4, 26);
    lv_obj_set_flex_flow(ui_cnt4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_cnt4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cnt4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_cnt4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cnt4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cnt4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cnt4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiIP = lv_label_create(ui_cnt4);
    lv_obj_set_width(ui_lblWifiIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiIP, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblWifiIP, "IP: ...");

    ui_lblWifiRSSI = lv_label_create(ui_cnt4);
    lv_obj_set_width(ui_lblWifiRSSI, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblWifiRSSI, LV_SIZE_CONTENT);
    lv_label_set_text(ui_lblWifiRSSI, "Signal: ...");

    ui_cntWifiBottom = lv_obj_create(ui_cntWifi);
    lv_obj_remove_style_all(ui_cntWifiBottom);
    lv_obj_set_height(ui_cntWifiBottom, 35);
    lv_obj_set_width(ui_cntWifiBottom, lv_pct(100));
    lv_obj_set_x(ui_cntWifiBottom, 0);
    lv_obj_set_y(ui_cntWifiBottom, -1);
    lv_obj_set_align(ui_cntWifiBottom, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_cntWifiBottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Button Close
    ui_btnWifiManagerClose = ui_button_create(ui_cntWifiBottom);
    lv_obj_set_x(ui_btnWifiManagerClose, 0);
    lv_obj_set_y(ui_btnWifiManagerClose, 0);
    lv_obj_set_align(ui_btnWifiManagerClose, LV_ALIGN_TOP_RIGHT);

    ui_lblWifiManagerClose = ui_comp_get_child(ui_btnWifiManagerClose, UI_COMP_BUTTON_LABEL);
    lv_label_set_text(ui_lblWifiManagerClose, "Close");

    // Keyboard
    ui_Keyboard = lv_keyboard_create(ui_screenWifi);
    lv_obj_set_width(ui_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_Keyboard, lv_pct(50));
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_outline_color(ui_Keyboard, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Keyboard, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Keyboard, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlWifiSpinner = lv_obj_create(ui_screenWifi);
    lv_obj_set_width(ui_pnlWifiSpinner, 125);
    lv_obj_set_height(ui_pnlWifiSpinner, 125);
    lv_obj_set_align(ui_pnlWifiSpinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlWifiSpinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlWifiSpinner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiSpinner = lv_spinner_create(ui_pnlWifiSpinner);
    lv_spinner_set_anim_params(ui_wifiSpinner, 1000, 90);
    lv_obj_set_width(ui_wifiSpinner, 80);
    lv_obj_set_height(ui_wifiSpinner, 80);
    lv_obj_set_align(ui_wifiSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_txtWifiPass, ui_event_txtWifiPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiAction, ui_event_btnWifiAction, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiScan, ui_event_btnWifiScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiManagerClose, ui_event_btnWifiManagerClose, LV_EVENT_ALL, NULL);

}
